### Add geolocation (POST)
POST http://127.0.0.1:8000/geolocation
Content-Type: application/json

{
  "ip_or_url": "8.8.8.8"
}

### Add geolocation (POST)
POST http://127.0.0.1:8000/geolocation
Content-Type: application/json

{
  "ip_or_url": "www.google.pl"
}

### Fetch by ip (GET)
GET http://127.0.0.1:8000/geolocation?ip_or_url=8.8.8.8
Content-Type: application/json

### Fetch by ID (GET)
GET http://127.0.0.1:8000/geolocation?id=2
Content-Type: application/json

### Fetch all(GET)
GET http://127.0.0.1:8000/geolocation/
Content-Type: application/json


### Delete only by ID (DELETE)
DELETE http://127.0.0.1:8000/geolocation/2
Content-Type: application/json

